run_metadata:
  default_input_namespace: testing
  description: SEIRS Model julia registration

register:
- namespace: PSU
  full_name: Pennsylvania State University
  website: https://ror.org/04p491231

- external_object: SEIRS_model/parameters
  namespace_name: PSU
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/static_params_SEIRS.csv
  title: Static parameters of the model
  description: Static parameters of the model
  identifier: https://doi.org/10.1038/s41592-020-0856-2
  file_type: csv
  release_date: 2020-06-01T12:00
  version: "1.0.0"
  primary: False
