run_metadata:
  description: Aliasing example
  local_data_registry_url: https://localhost:8000/api/
  remote_data_registry_url: https://data.scrc.uk/api/
  default_input_namespace: testing
  default_output_namespace: testing
  write_data_store: /Users/Soniam/.fair/datastore/
  local_repo: /media/martin/storage/projects/AtomProjects/DataPipeline.jl/
  latest_commit: 221bfe8b52bbfb3b2dbdc23037b7dd94b49aaa70
  remote_repo: https://github.com/FAIRDataPipeline/DataPipeline.jl
  public: true
  script: julia examples/simple2/main.jl

read:
- data_product: human/population
  use:
    data_product: scotland/human/population
    version: 0.1.0
    namespace: johnsmith

write:
- data_product: human/outbreak-timeseries
  description: data product description
  use:
    data_product: scotland/human/outbreak-timeseries
    version: 0.1.0
- data_product: human/outbreak/simulation_run
  description: another data product description
  use:
    data_product: human/outbreak/simulation_run-${{RUN_ID}}
    version: 0.1.0
