run_metadata:
  description: Read point estimate
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: http://data.scrc.uk/api/
  default_input_namespace: testing
  default_output_namespace: testing
  write_data_store: /Users/Soniam/.fair/datastore/
  local_repo: /media/martin/storage/projects/AtomProjects/DataPipeline.jl/
  latest_commit: 221bfe8b52bbfb3b2dbdc23037b7dd94b49aaa70
  remote_repo: https://github.com/FAIRDataPipeline/DataPipeline.jl
  public: true
  script: julia examples/simple2/main.jl

read:
- data_product: test/estimate/asymptomatic-period
  use:
    version: 0.0.1
