run_metadata:
  description: Raise issue with component
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: http://data.scrc.uk/api/
  default_input_namespace: martinburke
  default_output_namespace: martinburke
  write_data_store: /media/martin/storage/projects/AtomProjects/DataPipeline.jl/examples/simple2/data/
  local_repo: /media/martin/storage/projects/AtomProjects/DataPipeline.jl/
  latest_commit: 221bfe8b52bbfb3b2dbdc23037b7dd94b49aaa70
  remote_repo: https://github.com/FAIRDataPipeline/DataPipeline.jl
  script: julia examples/simple2/main.jl

write:
- data_product: test/array/issues/component
  description: a test array
  use:
    version: 0.1.0
- data_product: test/array/issues/whole
  description: a test array
  file_type: csv
  use:
    version: 0.1.0
