git:
  local_repo: /home/runner/work/DataPipeline.jl/DataPipeline.jl
  remote: origin
  remote_repo: git@notagit.com/user/project.git
namespaces:
  input: testing
  output: testing
registries:
  origin:
    data_store: /home/runner/work/DataPipeline.jl/DataPipeline.jl/docs/build/data
    token: /home/runner/work/DataPipeline.jl/DataPipeline.jl/docs/build/token
    uri: http://127.0.0.1:8001/api/
user:
  email: test@noreply.com
  family_name: Test
  github: FAIRDataPipeline
  given_names: Interface
  orcid: 000-0000-0000-0000
  uri: https://github.com/FAIRDataPipeline
  uuid: 2ddb2358-84bf-43ff-b2aa-3ac7dc3b49f1
