data_directory: data
access_log: access-{run_id}.yaml
fail_on_hash_mismatch: False
namespace: SCRC

read:
  - where:  # estimates
      data_product: human/infection/SARS-CoV-2/infectious-duration
      component: infectious-duration
  - where:
      data_product: human/infection/SARS-CoV-2/symptom-delay
      component: symptom-delay
  - where:
      data_product: human/infection/SARS-CoV-2/latent-period
      component: latent-period
  - where:  # arrays
      data_product: records/SARS-CoV-2/scotland/cases_and_management
  - where:  # table
      data_product: geography/scotland/lookup_table
