DROP TABLE IF EXISTS h5_array;
DROP TABLE IF EXISTS arr_dim;
DROP TABLE IF EXISTS arr_dim_name;

-- WIP
CREATE TABLE IF NOT EXISTS h5_array(
	arr_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	dp_id	INTEGER NOT NULL,
	tbl_cube TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS arr_dim(
	dim_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	arr_id INTEGER NOT NULL,
	dim_title TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS arr_dim_name(
	dim_name_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	dim_id INTEGER NOT NULL,
	dim_key INTEGER NOT NULL,
	dim_val TEXT NOT NULL
);
