DROP TABLE IF EXISTS h5_array;
DROP TABLE IF EXISTS arr_dim;
DROP TABLE IF EXISTS arr_dim_name;

-- WIP
CREATE TABLE IF NOT EXISTS h5_array(
	arr_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	dp_id	INTEGER NOT NULL,
	tbl_data TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS array_dim(
	dim_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	comp_id INTEGER NOT NULL,
	dim_index INTEGER NOT NULL,
	dim_type INTEGER NOT NULL,
	dim_title TEXT NOT NULL,
	dim_size INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS array_dim_name(
	dim_name_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	dim_id INTEGER NOT NULL,
	dim_val TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS toml_component(
	comp_id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	dp_id	INTEGER NOT NULL,
	comp_name	TEXT
);
