# model
model_name: "DataPipeline simple example"
model_repo: "https://github.com/FAIRDataPipeline/DataPipeline.jl"
# NB. ^ because the example is part of this package - replace with your own repo
model_version: "0.0.6"
model_description: "A simple SEIR simulation for demonstrating use of the DataPipeline.jl package [v0.4.1]"
model_website: "https://mjb3.github.io/DiscretePOMP.jl/stable/"
# NB. ^ in this case, the simulation model is borrowed from a different package with its own website

# simulation parameters
random_seed: 1
initial_s: 1000   # initial population size
max_t: 180.0      # simulation time
beta: 0.7         # contact rate := beta SI / N
