git:
  local_repo: /home/runner/work/DataPipeline.jl/DataPipeline.jl
  remote: origin
namespaces:
  input: testing
  output: testing
registries:
  origin:
    data_store: null
    token: null
    uri: http://localhost:8001/api/
user:
  email: test@noreply
  family_name: Test
  given_names: Interface
  orcid: null
  uuid: 2ddb2358-84bf-43ff-b2aa-3ac7dc3b49f1
