run_metadata:
  default_input_namespace: testing
  default_output_namespace: testing
  description: SEIRS Model julia
  script: |
    julia --project=examples/fdp -e "using Pkg; Pkg.instantiate()"
    julia --project=examples/fdp examples/fdp/seirs_sim.jl

register:
- namespace: PSU
  full_name: Pennsylvania State University
  website: https://ror.org/04p491231

- external_object: SEIRS_model/parameters
  namespace_name: PSU
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/DataPipeline.jl/updated-deps/examples/fdp/static_params_SEIRS.csv
  title: Static parameters of the model
  description: Static parameters of the model
  identifier: https://doi.org/10.1038/s41592-020-0856-2
  file_type: csv
  release_date: 2021-09-20T12:00
  version: "1.0.0"
  primary: False

write:
- data_product: model_output
  description: SEIRS model results
  file_type: csv
  use: 
    data_product: SEIRS_model/results/model_output/julia

- data_product: figure
  description: SEIRS output plot
  file_type: pdf
  use: 
    data_product: SEIRS_model/results/figure/julia
