run_metadata:
  description: pre_example stuff
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: http://data.scrc.uk/api/
  default_input_namespace: martinburke
  default_output_namespace: martinburke
  write_data_store: /media/martin/storage/projects/AtomProjects/DataPipeline.jl/examples/simple2/data/
  local_repo: /media/martin/storage/projects/AtomProjects/DataPipeline.jl/
  latest_commit: 221bfe8b52bbfb3b2dbdc23037b7dd94b49aaa70
  remote_repo: https://github.com/FAIRDataPipeline/DataPipeline.jl
  script: julia examples/fdp/main.jl

write:
- data_product: example/estimate/contact-parameter
  description: contact parameter
  use:
    version: 0.0.1
- data_product: example/estimate/asymptomatic-period
  description: asymptomatic period
  use:
    version: 0.0.1
- data_product: example/estimate/recovery-period
  description: recovery period
  use:
    version: 0.0.1
- data_product: example/estimate/mortality-rate
  description: mortality rate
  use:
    version: 0.0.1
