name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
      - name: Install dependencies
        run: |
            import Pkg
            Pkg.develop(Pkg.PackageSpec(path=pwd()))
            Pkg.instantiate()
        shell: julia --project=docs/ --color=yes {0}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install local registry
        run: /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
      - name: Checkout FAIRDataPipeline/FAIR-CLI
        uses: actions/checkout@v2
        with:
          repository: FAIRDataPipeline/FAIR-CLI
          path: FAIR-CLI
      - name: Move FAIR-CLI
        run: mv FAIR-CLI ../FAIR-CLI
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install and initialise FAIR CLI
        run: |
          cd ../FAIR-CLI
          poetry install
          source .venv/bin/activate
          cd ${{ github.workspace }}
          fair init --ci
          fair init --export ci.yaml

      - name: Build and deploy
        run: |
          mkdir tmp
          echo "#!/bin/sh" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "cd ../DataPipeline.jl" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "git config --local user.name "$GITHUB_ACTOR" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "cd ../DataPipeline.jl" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "julia --project=docs/ --color=yes docs/make.jl" >> ${{ github.workspace }}/tmp/tmp_file.sh
          chmod +x tmp/tmp_file.sh
          cd ../FAIR-CLI
          ls ../DataPipeline.jl/tmp/
          poetry run ../DataPipeline.jl/tmp/tmp_file.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_EVENT_NAME: push
