name: JuliaNightly
# Nightly Scheduled Julia Nightly Run
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  schedule:
    - cron: '0 2 * * 0'  # Weekly at 2 AM UTC Sunday

jobs:
  test:
    name: Julia Nightly - Ubuntu - x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up julia
        uses: julia-actions/setup-julia@v1
        with:
          version: nightly
          arch: x64
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install and initialise FAIR CLI
        run: |
          python -m venv venv
          source venv/bin/activate
          pip3 install fair-cli
          fair registry install
          fair init --ci
          fair registry start

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
        continue-on-error: true 
