name: JuliaNightly
# Nightly Scheduled Julia Nightly Run
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  schedule:
    - cron: '0 2 * * 0'  # Weekly at 2 AM UTC Sunday

jobs:
  test:
    name: Julia Nightly - Ubuntu - x64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: nightly
        arch: x64
    - name: Build package
      uses: julia-actions/julia-buildpkg@v1
    - name: Fix manifest for nightly Julia
      run: |
        using Pkg
        Pkg.activate(".")
        Pkg.resolve()
        Pkg.activate("examples/fdp")
        Pkg.resolve()
      shell: julia --color=yes {0} 
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install graphviz and venv
      run: |
        # Create venv
        python3 -m venv .venv
        sudo apt-get install graphviz
      shell: bash
    - name: Install and start remote registry
      run: |
        # Activate venv
        source .venv/bin/activate
        # Install fair-cli
        pip3 install fair-cli
        # Install remote registry
        mkdir ${{ github.workspace }}/.registry
        curl -fsSL https://data.fairdatapipeline.org/static/remoteregistry.sh | /bin/bash -s -- -d ${{ github.workspace }}/.registry/registry-rem -s drams.test-remote-settings -u admin -p admin
        # Start the remote registry
        script=${{ github.workspace }}/.registry/registry-rem/scripts/start_fair_registry
        echo $script
        $script -p 8001 -s drams.test-remote-settings
        # Copy the remote token
        cp ${{ github.workspace }}/.registry/registry-rem/token $PWD/token
        deactivate
    - name: Initialise and run fair-cli
      run: |
        source .venv/${ACTIVATE_DIR}/activate
        fair registry install
        fair registry start
        fair init --ci
        fair pull --debug examples/fdp/SEIRSconfig.yaml
        fair run --debug --dirty examples/fdp/SEIRSconfig.yaml
        deactivate
      shell: bash
      env:
        ACTIVATE_DIR: ${{ runner.os == 'Windows' && 'Scripts' || 'bin' }}
      # working-directory: julia_example # Use the julia_example Directory
    - name: Run tests
      uses: julia-actions/julia-runtest@v1
      env:
        WORKSPACE: ${{ github.workspace }}
        ACTIVATE_DIR: 'bin'
      with:
        prefix: ${{ github.workspace }}/test/runtests.sh
