name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  dp-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        julia-version:
          - '1.4'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
#          - windows-latest
        arch:
          - x64
        experimental:
          - false
      fail-fast: false
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
    - name: Build package
      uses: julia-actions/julia-buildpkg@master
    - name: Install local registry
      run: /bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
    
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Checkout FAIRDataPipeline/FAIR-CLI
      uses: actions/checkout@v2
      with:
        repository: FAIRDataPipeline/FAIR-CLI
        path: FAIR-CLI
    - name: Move FAIR-CLI
      run: mv FAIR-CLI ../FAIR-CLI
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install and initialise FAIR CLI
      run: |
        cd ../FAIR-CLI
        poetry install
        source .venv/bin/activate
        cd ${{ github.workspace }}
        fair init --ci

    - name: Running
      uses: julia-actions/julia-runtest@master
    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info
    - name: Codecov
      uses: codecov/codecov-action@v1
