name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  pipeline-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        julia-version:
          - '1.6'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        experimental:
          - false
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
    - name: Build package
      uses: julia-actions/julia-buildpkg@v1
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install graphviz
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install graphviz
        elif [ "$RUNNER_OS" == "Darwin" ]; then
            brew install graphviz
        fi
      shell: bash
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install and initialise FAIR CLI non-Windows
      if: matrix.os != 'windows-latest'
      run: |
        python -m venv venv
        source venv/bin/activate
        pip3 install fair-cli
        fair registry install
        fair init --ci
        fair registry start
    - name: Install and initialise FAIR CLI on Windows
      if: matrix.os == 'windows-latest'
      run: |
        pip3 install fair-cli
        fair registry install
        fair init --ci
        fair registry start
    - name: Running
      uses: julia-actions/julia-runtest@v1
    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./lcov.info
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        files: lcov.info
